### ISSUE TITLE
Includes in pairing.c

### ISSUE THREAD

**Issue by GermanSheepDog** [rainowen/ESP32_HomeKit_Demo#1]
Hello,
where can I find the correct files for this include in pairing.c:
- #include "hkdf.h"
- #include "chacha20_poly1305.h"
- #include "ed25519.h"
My big problem is the proc "chacha20_poly1305_encrypt". I got an version with more parameters.

**Comment by rainowen** [comment]
@GermanSheepDog sorry, this an old project for homekit demo, I have forked from https://github.com/younghyunjo/esp32-homekit
